
# ===============================
# Application
# ===============================
spring.application.name=rate-limiter

# ===============================
# Redis Configuration
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Server
# ===============================
server.port=8080

# ==========================
# Rate Limiter Configuration
# ==========================
rate-limiter.max-requests=5
rate-limiter.window=1m