services:

  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis-distributed

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis-distributed-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  rate-limiter-1:
    build:
      context: ..
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      RATE_LIMIT_MAX_REQUESTS: 5
      RATE_LIMIT_WINDOW: 1m

    depends_on:
      redis:
        condition: service_healthy


  rate-limiter-2:
    build:
      context: ..
      dockerfile: Dockerfile

    ports:
      - "8081:8080"

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      RATE_LIMIT_MAX_REQUESTS: 5
      RATE_LIMIT_WINDOW: 1m

    depends_on:
      redis:
        condition: service_healthy


volumes:
  redis-distributed-data: